- name: nginx
  source_files:
    - /tmp/access.log
  static_config:
    service: ucenter
  relabel_config:
    source_labels:
      - status
      - request
      - http_host
      - server_port
      - upstream_addr
      - request_method
      - upstream_status
    replacements:
      request:
        - trims:
          - sep: " "
            idx: 1
          - sep: "&"
            idx: 0
          replaces:
          - target: (.*)\?uid=(.*)
            value: $1?pid=$2
          - target: (.*)\?pid=(.*)
            value: $1?xxx=$2
        - trims:
          - sep: "?"
            idx: 0
  histogram_buckets:
    start: 50
    step: 50
    num: 1