- name: nginx
  source_files:
    - /data/logs/nginx/ucenter_access.log
  static_config:
    service: user_center
  relabel_config:
    source_labels:
      - status
      - request
      - http_host
      - server_port
      - upstream_addr
      - request_method
      - upstream_status
    replacement:
      request:
        trim: "?"
        replace:
          - target: ^[A-Z]+ /
            value: /
          - target: (.*)/[0-9]+/(.*)
            value: $1/xxx/$2
  histogram_buckets:
    start: 5.0
    step: 5.0
    num: 800