- name: nginx
  source_files:
    - /data/logs/nginx/service_nginx_80.log
  static_config:
    service: user_center
  relabel_config: 
    source_labels: 
      - request
      - method
      - status
    replacement:
      request: 
        trim: "?"
        replace:
          - target: /app/[0-9]+/api
            value: /app/xxx/api
